fix(xarray): roll back version to 2024.2.0
Xarray version 2024.3.0 introduces an error when I call
`xarray.DataArray.isnull`, with the final traceback `AttributeError:
'ScipyArrayWrapper' object has no attribute 'oindex'`

See issue here: https://github.com/pydata/xarray/issues/8909